name: CI/CD Pipeline
on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build-and-push-to-yc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # Укажите нужную версию .NET, если требуется
      - name: Build Docker image
        run: docker build ./prac6_1000 --tag cr.yandex/${{secrets.YC_REGISTRY_ID}}/microservices:latest
      - name: Login to YC Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: json_key
          password: ${{secrets.YC_KEYS}}
      - name: Push tag to YC Registry
        run: docker push cr.yandex/${{secrets.YC_REGISTRY_ID}}/microservices:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-push-to-yc]
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{secrets.YC_KEYS}}
          container-name: ${{secrets.YC_CONTAINER_NAME}}
          folder-id: ${{secrets.YC_FOLDER_ID}}
          revision-image-url: cr.yandex/${{secrets.YC_REGISTRY_ID}}/microservices:latest
          revision-service-account-id: ${{secrets.YC_SA_ID}}